export const SET_LOADING = 'SET_LOADING';

export const POST_TRIP = 'POST_TRIP';
export const GET_TRIP = 'GET_TRIP';

export const SET_CURRENT_TRIP = 'SET_CURRENT_TRIP';

export const GET_STRIDE_REQUEST = 'GET_STRIDE_REQUEST';
export const SET_STRIDE_REQUEST = 'SET_STRIDE_REQUEST';

export const ACCEPT_STRIDE_REQUEST = 'ACCEPT_STRIDE_REQUEST';
export const START_STRIDE_REQUEST = 'START_STRIDE_REQUEST';
export const END_STRIDE_REQUEST = 'END_STRIDE_REQUEST';

export const GET_CURRENT_WALKER = 'GET_CURRENT_WALKER';
export const SET_CURRENT_WALKER = 'SET_CURRENT_WALKER';

export const GET_COORDINATES = 'GET_COORDINATES';

export const SEND_LIVE_LOCATION = 'SEND_LIVE_LOCATION';
export const GET_LIVE_LOCATION = 'GET_LIVE_LOCATION';
export const SET_LIVE_LOCATION = 'SET_LIVE_LOCATION';